"""Initial schema

Revision ID: 1bd36d62e6d4
Revises: 
Create Date: 2026-08-25 19:08:38.144440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd36d62e6d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('provider_native_id', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('affected_entities', sa.JSON(), nullable=False),
    sa.Column('effective_date', sa.String(length=50), nullable=True),
    sa.Column('sunset_date', sa.String(length=50), nullable=True),
    sa.Column('source_artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_native_id', name='uq_provider_change')
    )
    op.create_table('raw_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_revision', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('storage_ref', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'source_key', 'content_hash', name='uq_raw_artifact')
    )
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('github_full_name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_organization_id'), 'repositories', ['organization_id'], unique=False)
    op.create_table('task_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dispatched_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.create_table('maintenance_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('provider_change_id', sa.Uuid(), nullable=False),
    sa.Column('base_revision_sha', sa.String(length=40), nullable=False),
    sa.Column('state', sa.Enum('DISCOVERED', 'IMPACT_ANALYZING', 'UNAFFECTED', 'AFFECTED_ACTION_REQUIRED', 'MIGRATING', 'VERIFYING', 'PR_OPEN', 'RESOLVED', 'SUPPRESSED', 'CANCELLED', 'STALE', 'MANUALLY_RESOLVED', 'HUMAN_INTERVENTION_REQUIRED', name='maintenancecasestate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'provider_change_id', 'base_revision_sha', name='uq_maintenance_case')
    )
    op.create_index(op.f('ix_maintenance_cases_organization_id'), 'maintenance_cases', ['organization_id'], unique=False)
    op.create_table('patch_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('base_commit_sha', sa.String(length=40), nullable=False),
    sa.Column('archive_content_hash', sa.String(length=64), nullable=False),
    sa.Column('affected_files', sa.JSON(), nullable=False),
    sa.Column('patch_data', sa.String(), nullable=False),
    sa.Column('patch_hash', sa.String(length=64), nullable=True),
    sa.Column('pre_image_hashes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_artifacts_organization_id'), 'patch_artifacts', ['organization_id'], unique=False)
    op.create_table('provider_change_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_change_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('source_artifact_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('evidence_source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_change_id'], ['provider_changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_change_id', 'revision_number', name='uq_provider_change_revision')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('archive_content_hash', sa.String(length=64), nullable=False),
    sa.Column('code_model_version', sa.String(length=50), nullable=False),
    sa.Column('dependency_graph', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_organization_id'), 'snapshots', ['organization_id'], unique=False)
    op.create_table('impact_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('evidence_level', sa.String(length=50), nullable=False),
    sa.Column('affected_files', sa.JSON(), nullable=False),
    sa.Column('evidence_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['maintenance_cases.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_assessments_organization_id'), 'impact_assessments', ['organization_id'], unique=False)
    op.create_table('migration_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'GENERATING', 'VERIFYING', 'PR_CREATED', 'BLOCKED', 'GENERATION_FAILED', 'VERIFICATION_FAILED', 'INFRASTRUCTURE_FAILED', 'STALE', 'CANCELLED', 'HUMAN_INTERVENTION_REQUIRED', name='migrationstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['maintenance_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_campaigns_organization_id'), 'migration_campaigns', ['organization_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('patch_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('github_pr_url', sa.String(), nullable=False),
    sa.Column('head_branch', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['maintenance_cases.id'], ),
    sa.ForeignKeyConstraint(['patch_artifact_id'], ['patch_artifacts.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_organization_id'), 'pull_requests', ['organization_id'], unique=False)
    op.create_table('migration_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('patch_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['migration_campaigns.id'], ),
    sa.ForeignKeyConstraint(['patch_artifact_id'], ['patch_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_attempts_organization_id'), 'migration_attempts', ['organization_id'], unique=False)
    op.create_table('verification_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('patch_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('sandbox_task_id', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'VERIFIED', 'BASELINE_FAILED', 'PATCH_CONFLICT', 'TESTS_FAILED', 'VERIFICATION_INTEGRITY_FAILED', 'INFRASTRUCTURE_FAILED', 'TIMEOUT', 'EXPIRED', 'CANCELLED', 'NO_TEST_COMMAND', name='verificationstate'), nullable=False),
    sa.Column('verification_plan', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('audit_passed', sa.Boolean(), nullable=True),
    sa.Column('signing_secret', sa.String(length=128), nullable=True),
    sa.Column('nonce', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['migration_campaigns.id'], ),
    sa.ForeignKeyConstraint(['patch_artifact_id'], ['patch_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_runs_organization_id'), 'verification_runs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_runs_organization_id'), table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_migration_attempts_organization_id'), table_name='migration_attempts')
    op.drop_table('migration_attempts')
    op.drop_index(op.f('ix_pull_requests_organization_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_migration_campaigns_organization_id'), table_name='migration_campaigns')
    op.drop_table('migration_campaigns')
    op.drop_index(op.f('ix_impact_assessments_organization_id'), table_name='impact_assessments')
    op.drop_table('impact_assessments')
    op.drop_index(op.f('ix_snapshots_organization_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('provider_change_revisions')
    op.drop_index(op.f('ix_patch_artifacts_organization_id'), table_name='patch_artifacts')
    op.drop_table('patch_artifacts')
    op.drop_index(op.f('ix_maintenance_cases_organization_id'), table_name='maintenance_cases')
    op.drop_table('maintenance_cases')
    op.drop_table('webhook_deliveries')
    op.drop_table('task_outbox')
    op.drop_index(op.f('ix_repositories_organization_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('raw_artifacts')
    op.drop_table('provider_changes')
    op.drop_table('organizations')
    # ### end Alembic commands ###
