"""Distributed locks and circuit breaker

Revision ID: 360f71341416
Revises: 1bd36d62e6d4
Create Date: 2026-08-25 19:21:28.551102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360f71341416'
down_revision: Union[str, Sequence[str], None] = '1bd36d62e6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breaker_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_failure_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('resource_leases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_leases_organization_id'), 'resource_leases', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_leases_organization_id'), table_name='resource_leases')
    op.drop_table('resource_leases')
    op.drop_table('circuit_breaker_states')
    # ### end Alembic commands ###
