/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars, react/no-unescaped-entities, @typescript-eslint/no-unused-expressions */
import Link from 'next/link';
import { apiClient, fetchApi } from '@/api/client';
import type { components } from '@/api/schema';

type PullRequestResponse = components["schemas"]["PullRequestResponse"];

export default async function PullRequestsPage() {
  let prsData: { items: PullRequestResponse[], total: number, page: number, size: number };
  try {
    prsData = await fetchApi(apiClient.GET('/api/v1/pull-requests/', {
      params: { query: { page: 1, size: 50 } }
    }));
  } catch (err) {
    console.error(err);
    prsData = { items: [], total: 0, page: 1, size: 50 };
  }

  return (
    <>
      <div className="page-header">
        <h1 className="page-title">Pull Requests</h1>
        <p className="page-subtitle">Track and review automated patches generated by API Guardian.</p>
      </div>
      
      {prsData.items.length > 0 ? (
        <div className="table-container">
          <table className="data-table">
            <thead>
              <tr>
                <th>Repository</th>
                <th>PR Number</th>
                <th>Case ID</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Link</th>
              </tr>
            </thead>
            <tbody>
              {prsData.items.map((pr: any) => (
                <tr key={pr.id}>
                  <td className="text-mono">{pr.repository_id.substring(0, 8)}...</td>
                  <td style={{ fontWeight: 500 }}>#{pr.github_pr_number}</td>
                  <td className="text-mono">
                    <Link href={`/cases/${pr.case_id}`} style={{ color: 'var(--primary)' }}>
                      {pr.case_id.substring(0, 8)}...
                    </Link>
                  </td>
                  <td>
                    <span className={`badge ${pr.state === 'OPEN' ? 'warning' : pr.state === 'MERGED' ? 'success' : 'default'}`}>
                      {pr.state}
                    </span>
                  </td>
                  <td style={{ color: 'var(--text-muted)' }}>{pr.created_at ? new Date(pr.created_at).toLocaleString() : 'N/A'}</td>
                  <td>
                    <a href={pr.github_pr_url} target="_blank" rel="noopener noreferrer" className="btn btn-sm btn-secondary">
                      View on GitHub
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="empty-state">
          <svg className="empty-state-icon" viewBox="0 0 24 24" width="48" height="48" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round" strokeLinejoin="round">
            <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
            <path d="M12 21v-4"></path>
            <circle cx="12" cy="13" r="4"></circle>
            <circle cx="7" cy="17" r="4"></circle>
            <circle cx="17" cy="17" r="4"></circle>
          </svg>
          <h2 className="empty-state-title">No pull requests</h2>
          <p className="empty-state-description">
            When API Guardian successfully generates and verifies a patch for a breaking change, the pull request will appear here.
          </p>
        </div>
      )}
    </>
  );
}
