"""Diff parser for LLM generated patches."""

from pathlib import Path
from typing import ClassVar


class DiffValidationError(Exception):
    """Raised when a unified diff is invalid or modifies unauthorized files."""


from api_guardian.domain.migration import MigrationScope


class UnifiedDiffParser:
    """Parses and validates unified diffs generated by LLMs against a MigrationScope."""

    FORBIDDEN_FILES: ClassVar[set[str]] = {
        ".env",
        ".env.example",
        "package.json",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "requirements.txt",
        "pyproject.toml",
        "poetry.lock",
        "setup.py",
        "setup.cfg",
    }

    FORBIDDEN_DIRS: ClassVar[set[str]] = {
        ".github/workflows",
    }

    def __init__(self, scope: MigrationScope) -> None:
        self.scope = scope

    def validate_patch(self, patch_data: str) -> list[str]:
        """
        Validates a unified diff string against the MigrationScope.
        Returns a list of affected files if valid.
        Raises DiffValidationError if invalid.
        """
        if not patch_data.strip():
            raise DiffValidationError("Empty patch")

        affected_files = set()
        added_lines = 0
        removed_lines = 0
        
        for line in patch_data.splitlines():
            if line.startswith("+") and not line.startswith("+++"):
                added_lines += 1
            elif line.startswith("-") and not line.startswith("---"):
                removed_lines += 1
                
            if line.startswith(("+++ ", "--- ")):
                path_str = line[4:].strip().split("\t")[0]
                if path_str.startswith(("a/", "b/")):
                    path_str = path_str[2:]
                
                if path_str == "/dev/null":
                    continue
                    
                if path_str.startswith("/") or ".." in path_str:
                    raise DiffValidationError(f"Path traversal detected: {path_str}")
                
                path = Path(path_str)
                is_test = "test" in path.parts or path.name.startswith("test_") or path.name.endswith("_test.py")
                
                # Check forbidden
                if path.name in self.FORBIDDEN_FILES and path_str not in self.scope.allowed_config_modifications:
                    raise DiffValidationError(f"Modification to forbidden file: {path_str}")
                
                for parent in path.parents:
                    parent_str = str(parent)
                    if parent_str in self.FORBIDDEN_DIRS or f"/{parent_str}" in self.FORBIDDEN_DIRS:
                        raise DiffValidationError(f"Modification to forbidden directory: {path_str}")

                # Enforce scope
                if is_test:
                    if not self.scope.tests_modification_allowed:
                        raise DiffValidationError(f"Test modifications not allowed, but attempted to modify: {path_str}")
                    if path_str not in self.scope.allowed_test_files and path_str not in self.scope.allowed_directories:
                        raise DiffValidationError(f"Patch modifies un-assessed test file: {path_str}. Allowed tests: {self.scope.allowed_test_files}")
                else:
                    if path_str not in self.scope.allowed_source_files and not any(path_str.startswith(d) for d in self.scope.allowed_directories):
                        raise DiffValidationError(f"Patch modifies un-assessed source file: {path_str}. Allowed sources: {self.scope.allowed_source_files}")
                
                affected_files.add(path_str)

        if len(affected_files) > self.scope.max_changed_files:
            raise DiffValidationError(f"Patch modifies {len(affected_files)} files, which exceeds limit {self.scope.max_changed_files}")
            
        total_changed = added_lines + removed_lines
        if total_changed > self.scope.max_changed_lines:
            raise DiffValidationError(f"Patch modified {total_changed} lines, which exceeds limit {self.scope.max_changed_lines}")

        if not affected_files:
            raise DiffValidationError("Could not parse any modified files from diff")

        return list(affected_files)
